---
- hosts: rpi_cluster 
  remote_user: pi
  become: yes

  roles:
    - role: common
      tags: ['common']
    - role: k3s
      tags: ['k3s']
      #    - role: k8s_metallb
      #      delegate_to: localhost
      #      run_once: True
      #      tags: ['k8s_metallb']
