---

- name: Get k3s master IP
  set_fact:
    k3s_master_ip: "{{ hostvars[ k3s_master_host ].ansible_host }}"

- name: Read node-token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token
  delegate_to: "{{ k3s_master_host }}"

- name: Store Master node-token
  set_fact:
    k3s_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"            

- name: Copy K3s service file
  template:
    src: etc/systemd/system/k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0755
  notify: restart k3s
